#!/usr/bin/env python3
"""Derive split Vdbench GraphChi PSW workload templates from an edge list."""

from __future__ import annotations

import argparse
from pathlib import Path


EDGE_BYTES = 16


def read_edges(path: Path) -> list[tuple[int, int]]:
    edges: list[tuple[int, int]] = []
    with path.open(encoding="utf-8") as handle:
        for lineno, line in enumerate(handle, 1):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) != 2:
                raise SystemExit(f"{path}:{lineno}: expected two columns: src dst")
            edges.append((int(parts[0]), int(parts[1])))
    if not edges:
        raise SystemExit(f"{path}: no edges found")
    return edges


def interval_of(vertex: int, vertices_per_interval: int) -> int:
    return vertex // vertices_per_interval


def integer_percentages(counts: list[int]) -> list[int]:
    total = sum(counts)
    if total <= 0:
        raise ValueError("cannot normalize empty counts")
    raw = [count * 100 / total for count in counts]
    floors = [int(value) for value in raw]
    remainder = 100 - sum(floors)
    order = sorted(range(len(counts)), key=lambda idx: (raw[idx] - floors[idx], counts[idx]), reverse=True)
    pct = floors[:]
    for idx in order[:remainder]:
        pct[idx] += 1
    return pct


def derive_rows(
    edges: list[tuple[int, int]],
    intervals: int,
    vertices_per_interval: int,
    iterations: int,
    reheat_interval: int | None = None,
) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    phase_sequence = [
        (iteration, interval)
        for iteration in range(1, iterations + 1)
        for interval in range(intervals)
    ]
    if reheat_interval is not None:
        phase_sequence.append((iterations + 1, reheat_interval))

    for iteration, interval in phase_sequence:
        phase = f"iter{iteration}_i{interval}"
        counts = [0 for _ in range(intervals)]
        roles = ["not_accessed" for _ in range(intervals)]

        for src, dst in edges:
            src_i = interval_of(src, vertices_per_interval)
            dst_i = interval_of(dst, vertices_per_interval)
            if src_i < 0 or src_i >= intervals or dst_i < 0 or dst_i >= intervals:
                raise SystemExit(
                    f"edge ({src}, {dst}) outside intervals={intervals}, "
                    f"vertices_per_interval={vertices_per_interval}"
                )

            # GraphChi PSW Algorithm 3:
            # - readFully() reads the current memory shard by destination interval.
            # - readNextWindow(a,b) reads out-edges from the current source interval
            #   in non-current shards.
            if dst_i == interval:
                counts[interval] += 1
                roles[interval] = "memory_shard"
            elif src_i == interval:
                counts[dst_i] += 1
                roles[dst_i] = "sliding_shard"

        pct = integer_percentages(counts)
        for shard, count in enumerate(counts):
            rows.append(
                {
                    "phase": phase,
                    "iteration": str(iteration),
                    "interval": str(interval),
                    "object_id": f"shard_{shard:02d}",
                    "role": roles[shard],
                    "read_edges": str(count),
                    "read_bytes": str(count * EDGE_BYTES),
                    "target_ops_pct": str(pct[shard]),
                    "source": "generated_graph_plus_GraphChi_OSDI_2012_PSW",
                }
            )
    return rows


def template_header(title: str) -> list[str]:
    return [
        f"* GraphChi PSW vdbench v1 - {title}",
        "* AUTO-GENERATED by scripts/derive_profile.py",
        "* Source rule: GraphChi OSDI 2012 Parallel Sliding Windows readFully/readNextWindow.",
        "* See README.md and SOURCES.md before use.",
        "",
        "data_errors=1",
        "create_anchors=yes",
        "messagescan=no",
        "",
        "hd=default,vdbench=@VDBENCH_HOME@,user=@REMOTE_USER@,shell=ssh",
        "hd=hd1,system=@HOST1@",
        "",
        "fsd=default,depth=1,width=1,files=@FILES_PER_SHARD@,size=@FILE_SIZE@,shared=yes,openflags=o_direct",
    ]


def append_fsds(lines: list[str], intervals: int) -> None:
    for shard in range(intervals):
        lines.append(f"fsd=fsd_s{shard},anchor=@ANCHOR@/shard_{shard:02d}")


def write_prepare_template(path: Path, intervals: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = template_header("prepare only")
    append_fsds(lines, intervals)
    lines.append("")
    for shard in range(intervals):
        lines.append(f"fwd=prep_s{shard},fsd=fsd_s{shard},operation=read,threads=4")
    lines.append("")
    prep_list = ",".join(f"prep_s{shard}" for shard in range(intervals))
    lines.append(f"rd=prepare_clean,fwd=({prep_list}),format=(clean,only),fwdrate=max")
    lines.append(f"rd=prepare_create,fwd=({prep_list}),format=(restart,only),fwdrate=max")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_run_template(path: Path, rows: list[dict[str, str]], intervals: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    phases = list(dict.fromkeys(row["phase"] for row in rows))
    rows_by_phase = {phase: [row for row in rows if row["phase"] == phase] for phase in phases}

    lines = template_header("run only")
    lines.insert(8, "abort_failed_skew=2")
    append_fsds(lines, intervals)
    lines.append("")

    for phase in phases:
        for row in rows_by_phase[phase]:
            pct = int(row["target_ops_pct"])
            if pct <= 0:
                continue
            shard = int(row["object_id"].split("_")[1])
            lines.append(
                f"fwd={phase}_s{shard},fsd=fsd_s{shard},operation=read,"
                f"fileio=sequential,fileselect=random,xfersize=@XFER_SIZE@,"
                f"threads=@THREADS@,skew={pct}"
            )
        lines.append("")

    for phase in phases:
        active = [
            int(row["object_id"].split("_")[1])
            for row in rows_by_phase[phase]
            if int(row["target_ops_pct"]) > 0
        ]
        fwd_list = ",".join(f"{phase}_s{shard}" for shard in active)
        lines.append(f"rd={phase},fwd=({fwd_list}),fwdrate=@FWD_RATE@,elapsed=@PHASE_SECONDS@,interval=1")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--edges", default="datasets/smoke_edges.tsv")
    parser.add_argument("--prepare-template", default="configs/prepare_data.vdb.in")
    parser.add_argument("--run-template", default="configs/run_test.vdb.in")
    parser.add_argument("--intervals", type=int, default=4)
    parser.add_argument("--vertices-per-interval", type=int, default=128)
    parser.add_argument("--iterations", type=int, default=1)
    parser.add_argument("--reheat-interval", type=int, default=0)
    args = parser.parse_args()

    if args.reheat_interval < 0 or args.reheat_interval >= args.intervals:
        raise SystemExit(
            f"reheat interval {args.reheat_interval} outside intervals={args.intervals}"
        )

    edges = read_edges(Path(args.edges))
    rows = derive_rows(
        edges,
        args.intervals,
        args.vertices_per_interval,
        args.iterations,
        args.reheat_interval,
    )
    write_prepare_template(Path(args.prepare_template), args.intervals)
    write_run_template(Path(args.run_template), rows, args.intervals)
    print(
        f"derived {args.prepare_template} and {args.run_template} from {args.edges}; "
        f"phases={args.intervals * args.iterations + 1}"
    )


if __name__ == "__main__":
    main()
