#!/usr/bin/env python3
"""Derive WRF-group Vdbench templates from an object-level Zipf profile."""

from __future__ import annotations

import argparse
import math
from pathlib import Path


GROUPS = ("startup", "checkpoint", "history")
PHASES = (
    ("startup_read", "startup"),
    ("checkpoint_read", "checkpoint"),
    ("history_read", "history"),
    ("checkpoint_reheat", "checkpoint"),
)


def zipf_object_shares(object_count: int, alpha: float) -> list[float]:
    if object_count <= 0:
        raise ValueError("object_count must be positive")
    if not math.isfinite(alpha) or alpha <= 0:
        raise ValueError("alpha must be a positive finite number")

    weights = [index ** (-alpha) for index in range(1, object_count + 1)]
    total = sum(weights)
    return [weight * 100.0 / total for weight in weights]


def normalize_nonzero_percentages(raw: list[float]) -> list[int]:
    if not raw or len(raw) > 100:
        raise ValueError("raw percentages must contain between 1 and 100 entries")

    result = [max(1, math.floor(value + 0.5)) for value in raw]
    while sum(result) > 100:
        candidates = [index for index, value in enumerate(result) if value > 1]
        if not candidates:
            raise ValueError("cannot normalize percentages without producing a zero")
        index = max(candidates, key=lambda item: result[item] - raw[item])
        result[index] -= 1
    while sum(result) < 100:
        index = max(range(len(result)), key=lambda item: raw[item] - result[item])
        result[index] += 1
    return result


def aggregate_zipf_percentages(
    object_count: int,
    rank_count: int,
    alpha: float,
) -> list[int]:
    if object_count <= 0 or rank_count <= 0 or object_count % rank_count:
        raise ValueError("object_count must be positive and divisible by rank_count")

    shares = zipf_object_shares(object_count, alpha)
    objects_per_rank = object_count // rank_count
    raw = [
        sum(shares[index * objects_per_rank : (index + 1) * objects_per_rank])
        for index in range(rank_count)
    ]
    return normalize_nonzero_percentages(raw)


def template_header(title: str, *, check_skew: bool) -> list[str]:
    lines = [
        f"* WRF-derived vdbench Zipf v1 - {title}",
        "* AUTO-GENERATED by scripts/derive_zipf_profile.py",
        "* WRF supplies file lifecycle semantics; Zipf(0.99) is an execution model.",
        "* See README.md and SOURCES.md before use.",
        "",
        "data_errors=1",
        "create_anchors=yes",
        "messagescan=no",
    ]
    if check_skew:
        lines.append("abort_failed_skew=2")
    lines.extend(
        [
            "",
            "hd=default,vdbench=@VDBENCH_HOME@,user=@REMOTE_USER@,shell=ssh",
            "hd=hd1,system=@HOST1@",
            "",
            "fsd=default,depth=1,width=1,files=@FILES_PER_RANK@,"
            "size=@FILE_SIZE@,shared=yes,openflags=o_direct",
        ]
    )
    return lines


def append_fsds(lines: list[str], rank_count: int) -> None:
    for group in GROUPS:
        for rank in range(1, rank_count + 1):
            lines.append(
                f"fsd=fsd_{group}_r{rank:02d},"
                f"anchor=@ANCHOR@/{group}/rank_{rank:02d}"
            )


def build_prepare_template(rank_count: int) -> str:
    lines = template_header("prepare only", check_skew=False)
    append_fsds(lines, rank_count)
    lines.append("")

    prep_names: list[str] = []
    for group in GROUPS:
        for rank in range(1, rank_count + 1):
            name = f"prep_{group}_r{rank:02d}"
            prep_names.append(name)
            lines.append(
                f"fwd={name},fsd=fsd_{group}_r{rank:02d},"
                "operation=read,threads=@FORMAT_THREADS@"
            )

    joined = ",".join(prep_names)
    lines.extend(
        [
            "",
            f"rd=prepare_clean,fwd=({joined}),format=(clean,only),fwdrate=max",
            f"rd=prepare_create,fwd=({joined}),format=(restart,only),fwdrate=max",
        ]
    )
    return "\n".join(lines) + "\n"


def build_run_template(rank_count: int, weights: list[int]) -> str:
    if len(weights) != rank_count or sum(weights) != 100 or min(weights) <= 0:
        raise ValueError("weights must contain one positive percentage per rank and sum to 100")

    lines = template_header("run only", check_skew=True)
    append_fsds(lines, rank_count)
    lines.append("")

    for phase, group in PHASES:
        for rank, weight in enumerate(weights, 1):
            lines.append(
                f"fwd={phase}_r{rank:02d},fsd=fsd_{group}_r{rank:02d},"
                "operation=read,fileio=sequential,fileselect=random,"
                "xfersize=@XFER_SIZE@,threads=@THREADS@,"
                f"skew={weight}"
            )
        lines.append("")

    for phase, _group in PHASES:
        fwds = ",".join(f"{phase}_r{rank:02d}" for rank in range(1, rank_count + 1))
        lines.append(
            f"rd={phase},fwd=({fwds}),fwdrate=@FWD_RATE@,"
            "elapsed=@PHASE_SECONDS@,interval=1"
        )

    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prepare-template", default="configs/prepare_data.vdb.in")
    parser.add_argument("--run-template", default="configs/run_test.vdb.in")
    parser.add_argument("--rank-count", type=int, default=20)
    parser.add_argument("--objects-per-rank", type=int, default=480)
    parser.add_argument("--alpha", type=float, default=0.99)
    args = parser.parse_args()

    object_count = args.rank_count * args.objects_per_rank
    weights = aggregate_zipf_percentages(object_count, args.rank_count, args.alpha)

    prepare_path = Path(args.prepare_template)
    run_path = Path(args.run_template)
    prepare_path.parent.mkdir(parents=True, exist_ok=True)
    run_path.parent.mkdir(parents=True, exist_ok=True)
    prepare_path.write_text(build_prepare_template(args.rank_count), encoding="utf-8")
    run_path.write_text(build_run_template(args.rank_count, weights), encoding="utf-8")

    print(
        f"derived {prepare_path} and {run_path}; objects={object_count}; "
        f"alpha={args.alpha}; weights={'/'.join(map(str, weights))}"
    )


if __name__ == "__main__":
    main()
